// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ7lQZSLyaWrw1bONU3q5HGBpl7VChyZ0',
    appId: '1:673455496533:web:43a3acf5b098a5201ca3dc',
    messagingSenderId: '673455496533',
    projectId: 'trackit-360',
    authDomain: 'trackit-360.firebaseapp.com',
    storageBucket: 'trackit-360.firebasestorage.app',
    measurementId: 'G-SFFVD7Z4JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT6_3iJTwTKnwMl4jRm4phyOspDCjRfsc',
    appId: '1:673455496533:android:c7bbe346e80d3abc1ca3dc',
    messagingSenderId: '673455496533',
    projectId: 'trackit-360',
    storageBucket: 'trackit-360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhf-uxNyAx0LtOpcsJYSoLH83IvqFjpCI',
    appId: '1:673455496533:ios:edbd0056c9a613741ca3dc',
    messagingSenderId: '673455496533',
    projectId: 'trackit-360',
    storageBucket: 'trackit-360.firebasestorage.app',
    iosBundleId: 'com.example.athlete360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhf-uxNyAx0LtOpcsJYSoLH83IvqFjpCI',
    appId: '1:673455496533:ios:edbd0056c9a613741ca3dc',
    messagingSenderId: '673455496533',
    projectId: 'trackit-360',
    storageBucket: 'trackit-360.firebasestorage.app',
    iosBundleId: 'com.example.athlete360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ7lQZSLyaWrw1bONU3q5HGBpl7VChyZ0',
    appId: '1:673455496533:web:7137c240a145e72a1ca3dc',
    messagingSenderId: '673455496533',
    projectId: 'trackit-360',
    authDomain: 'trackit-360.firebaseapp.com',
    storageBucket: 'trackit-360.firebasestorage.app',
    measurementId: 'G-41N7ZVSK2F',
  );
}
